### ISSUE TITLE
Examples of Use

### ISSUE THREAD

**Issue by nsteele36** [0nza1101/leaflet-velocity-ts#2]
Bruh you literally copied the JavaScript from the other github repo. Could you provide an example actually using the velocity layer in TypeScript??

**Comment by 0nza1101** [comment]
What a descent way to call for help, I wonder if at least you know what’s a fork, a diff or even a README ? See my other repo [ionic3-leaflet-velocity](https://github.com/0nza1101/ionic3-leaflet-velocity) and  adapt it to your Typescript project.
