### ISSUE TITLE
Outdated project

### ISSUE THREAD

**Issue by AMarquis1** [0nza1101/leaflet-velocity-ts#4]
Hello, the optimisation you did with particle is mind blowing. Leaflet-velocity is very slow without what you did. Is there any chance you update the projet to add the features they added over the time? (exemple : the option for opacity, the two public methods( setData and setOptions and lets you modify the layer's propreties on the fly).

I can't use your fork because of that. I am forced to use the standard library, but it is killing me inside because of the buggy particle.

Merci ! :)

**Comment by 0nza1101** [comment]
Hello, originally I needed this library for an old leaflet.js based hybrid app project so I feel you with the buggy particle.
It's an old fork-based project that has changed over time. I have to integrate the minimal optimization of the main branch first. I'll try to take a look this weekend.

**Comment by AMarquis1** [comment]
Sweet, I can't wait to test it out, lmk when youre merging the branch :)
